### ISSUE TITLE
Missing resource(s)

### ISSUE THREAD

**Issue by acka47** [hbz/mabxml-elasticsearch#50]
Reported by today via email by D.S.:

> der folgende Link resultiert in einer Fehlermeldung:
> 
> http://lobid.org/hbz01/HT020172748

The resource is available via lobid-resources, though: http://lobid.org/resources/HT020172748

**Comment by dr0i** [comment]
The resource was missing in the daily mabxml updates. Strangely so!
Doing a re-dump it now _does_ reside in the produced DE-605-aleph-update-marcxchange-20190828-20190902.tar.gz.

Maybe one of the daily updates wasn't correctly done, at Sunday (DE-605-aleph-update-marcxchange-20190901-20190902.tar.gz) it is only 50KB sized (average is 15MB)), also the one made at Saturday is small (200KB). But then, isn't it expected that on weekend there is lesser data? Yes and no. Looking into the daily updates, it seems that most of the time the size even at the weekend is around 6MB (form 9. July to 17. August at least), but sometimes it is only a few KB (sometimes even totally empty).
So. No real clue what has happened.

**Comment by dr0i** [comment]
Btw, with this new made mabXmlDump the resource is indeed indexed into hbz01:
http://lobid.org/hbz01/HT020172748.

**Comment by dr0i** [comment]
Hold on, one thing comes to my mind:
this resource has a *aleph-publish* of *036364796*, which smells, because it is part of the one big jump don in the Verbundkatalog a month ago or so:
Although I thought doing the daily updates, the parameter "max" in the jdbc-program has no impact of the daily routine (it was indeed set to 1.5M, far away of the former 27.5M set in the basedumper), I set it to 45M. Maybe that is no somehow needed (to set the max sys number in the jdbc-programm to the max of the sysnumber of the hbz01-DB).
